### ISSUE TITLE
training optimization

### ISSUE THREAD

**Issue by wonlee2019** [lin-toto/lic-multistage-spatial-context#1]
Have you ever considered the training strategy, i.e., learning a low bitrate model from a well-trained high bitrate model.

Currently, I set the low bitrate for training and load the checkpoint of high bitrate model. But, it cannot work.

**Comment by lin-toto** [comment]
This actually should work as this is exactly how some of the retrained models are generated.

**Comment by wonlee2019** [comment]
HAHA! Tt is that I worry about. But I am trying to solve this with my new thought! 

Because the well-trained model has came to the largest epoch (50), so I just reset the training command with "--epochs 60". And it works.

And thanks CompressAI keeper to inspire me , haha!

And thank you toto!
